import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.sass";
import Providers from "./providers/providers";
import ChatsSidebar from "@/components/molecules/ChatsSidebar/ChatsSidebar";
import { SidebarTrigger } from "@/components/ui/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ChatsSidebar />
          <main className="w-full h-full">
            <SidebarTrigger />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
